#!/bin/sh

set -e

echo ">>> Build Customized HEVC Decoder"

#cd libde265
#./autogen.sh
#./configure
#cd ..

make -C libde265 -j12
sudo make install -C libde265

echo ">>> Extracting raw HEVC data stream"
#ffmpeg -y -i ../data/example.mp4 -c:v copy -bsf hevc_mp4toannexb -f hevc ../data/example.h265

#../build/dec265/dec265 ../data/example.h265
./libde265/sherlock265/sherlock265 ./data/example.h265

## HM related approach
#echo ">>> Decode the stream"
#../HM/bin/TAppDecoderStatic --BitstreamFile=../data/example.h265 --SkipFrames=0 --ReconFile=../data/example.yuv
#echo ">>> Encode the stream"
#ffmpeg -y -f rawvideo -pixel_format yuv420p -video_size 1472x668 -i ../data/example.yuv ../data/example.mkv
